import { useMemo, useState } from "react"
import { Link, useNavigate, useParams } from "react-router-dom"
import { Button } from "@tx/ui"
import {
  AgentSummonPanel,
  BookCoverPreview,
  CreativeStudioShell,
  InteriorStylingPanel,
  LayoutTypographyPanel,
  OpenPagePreview,
  StudioAgentSidebar,
} from "@tx/ui-lib"
import { useGittenbergData } from "@tx/gittenberg-data-react"
import { findBuildForEdition, findEdition, studioAgents } from "@/data/consumer-data"
import { editionIdParam, routes } from "@/navigation/routes"

const MOCK_COVERS = [
  "https://lh3.googleusercontent.com/aida-public/AB6AXuBinX7S3M-OXFGiLfhbfaDT4S_Cmzqpm5sSfGVBCDlheh2pRc82HE81pDGpkQnzDrJCL3wxxEfQ0qjYXiHr5MyF9SzBZP0VEHllk8LiG9AWGygHGa8eE_8ce3gr-_1ewZ3uQJfzjcbTqj9sdGaHh4C1hWzYY-6_6kzfo0GClGX2Wa-qNmhgGUWvCC7Lp3i9OltEbXLZYbv5qn81xlSDGlRjDKE9qYDzGOi5D3H6FMsUnZudTxnvajL786qSsRLBMH0dOaHQak5r4ngI",
  "https://lh3.googleusercontent.com/aida-public/AB6AXuBf8zrtHjLlM8lZwjYVyBdGl1xGVgLag_ajuH9rLvR3PsFcQv4bCw5_trAXwD_gtJqH82nBv81to-go-ZM5fl6sTI0jSn3A0-8MrqWUfA79vf5CAiiIX4LmsfqJ8YjRGAEuIHRyWZfcCywYmI4F_s0LtfeldjOT001iFAwO_f0tg7z8TCPIXuasfjO0k34Uk0ZHVTCyIzM1-9e_rpT1D7wsiBbfAoWBLrWw7bz4qngcxlHzCO3kahgUwHLcb4u91KNItSs5VkKpj1OD",
  "https://lh3.googleusercontent.com/aida-public/AB6AXuA8Lxob_cg6IJhCBW5Lsmo3PzkMXBNr2MMf-NNn65V6gvDqsv3a22lcL0bfHsFWoIZ6EWd4v2xzqVHn7MrDnYJ6aX0B6hFGwN28xog7--LLz3tOK16i3XfD5laIm66Tri5Q-_5M8lVVYfXoJJbIEx0Jj2kMbM9JKOUkJPcecgInxbrvQWdQ8zt0sAExssLpMWjKM-FwKCEejFByVhzAdI3vzXtWbMf7cRMC0JRKAzv4AYGZsuKYeKiz3Tz-CkYzFphp5NnTs0ciT03L",
]

export function CreativeStudioPage() {
  const navigate = useNavigate()
  const params = useParams<{ [editionIdParam]: string }>()
  const editionId = params[editionIdParam] ?? ""
  const data = useGittenbergData()
  const edition = findEdition(data.libraryEditions, editionId)
  const build = edition ? findBuildForEdition(data.literaryBuilds, edition) : undefined
  const session = data.creativeStudioSessions[0]
  const agents = useMemo(() => studioAgents(data.agents), [data.agents])

  const [selectedAgentId, setSelectedAgentId] = useState(
    session?.activeAgentId ?? agents[0]?.id ?? "",
  )
  const [intent, setIntent] = useState(session?.coverIntentPrompt ?? "")
  const [coverSrc, setCoverSrc] = useState(session?.coverAssetUrl ?? edition?.coverUrl ?? "")
  const [regenerating, setRegenerating] = useState(false)
  const [mockMessage, setMockMessage] = useState<string | null>(null)
  const [coverIndex, setCoverIndex] = useState(0)

  if (!edition) {
    return (
      <main className="mx-auto max-w-container-max px-boundary py-region">
        <p className="font-body-md text-on-surface-variant">Edition not found.</p>
        <Link to={routes.libraryCinematic} className="mt-component text-primary underline">
          Back to library
        </Link>
      </main>
    )
  }

  const agentChips = agents.map((agent) => ({
    ...agent,
    selected: agent.id === selectedAgentId,
  }))

  const handleRegenerate = () => {
    setRegenerating(true)
    setMockMessage(null)
    window.setTimeout(() => {
      const nextIndex = (coverIndex + 1) % MOCK_COVERS.length
      setCoverIndex(nextIndex)
      setCoverSrc(MOCK_COVERS[nextIndex] ?? coverSrc)
      setRegenerating(false)
      setMockMessage(
        "Cover regenerated by agent (mock). In production, this calls the creative studio orchestration API.",
      )
    }, 1200)
  }

  const buildId = build?.id ?? edition.primaryBuildId ?? "build-moby-primary"

  return (
    <main>
      <CreativeStudioShell
        preview={
          <div className="flex flex-col items-center gap-section">
            <BookCoverPreview title={edition.title} author={edition.author} coverSrc={coverSrc} />
            <OpenPagePreview
              paragraphs={[
                "The psychohistorical equations had long predicted the fall of the Galactic Empire.",
                "Hari Seldon's plan was not to stop the collapse, but to shorten the dark age that would follow.",
              ]}
            />
            {mockMessage ? (
              <p className="max-w-md text-center font-ui-label-sm text-secondary">{mockMessage}</p>
            ) : null}
            {regenerating ? (
              <p className="font-ui-label-sm text-on-surface-variant">Agent is composing cover art…</p>
            ) : null}
          </div>
        }
        sidebar={
          <StudioAgentSidebar
            activeTab="cover"
            coverPanel={
              <AgentSummonPanel
                agents={agentChips}
                intent={intent}
                onIntentChange={setIntent}
                onAgentSelect={setSelectedAgentId}
                onRegenerate={handleRegenerate}
              />
            }
            illustrationPanel={<InteriorStylingPanel />}
            layoutPanel={<LayoutTypographyPanel />}
          />
        }
        footer={
          <>
            <Button variant="outline">Save Draft</Button>
            <Button
              className="bg-primary text-on-primary"
              onClick={() => navigate(routes.printOrder(buildId, true))}
            >
              Send to Print Queue
            </Button>
          </>
        }
      />
    </main>
  )
}
